### ISSUE TITLE
Report class has incorrect field name

### ISSUE THREAD

**Issue by rmathew8-kust** [andrewthetechie/geekbot-api-py#19]
It appears that the Report class has an incorrect field name.. and there is no test coverage for this. The below change seems to fix the issue.
```
class Report(BaseModel):
    id: int
    slack_ts: Optional[str]
    standup_id: str
    timestamp: int
    channel: str
    is_anonymous: Optional[bool]
    member: User
    questions: List[Answer]
    # answers: List[Answer]
```

**Comment by andrewthetechie** [comment]
Hi Matthew,

Thanks for the report. I'd be happy to approve a PR that makes this change and adds testing for it!

**Comment by rmathew8-kust** [comment]
Hi - I'm trying to model my test for reports on the teams test, and am a bit unclear about the below.. could you clarify. thanks

```
def test_get_teams_one_team(test_client, fake_team):
    test_client["requests_mock"].get(
        # shouldn't this be json=[fake_team.dict()]
        url=test_client["client"].teams._get_request_path(), json=fake_team.dict()
    )
   ...
```

**Comment by andrewthetechie** [comment]
Hi Roy,

That test is testing that when the API returns a single team, instead of a list, that the code operates properly.

**Comment by andrewthetechie** [comment]
https://github.com/andrewthetechie/geekbot-api-py/pull/21

**Comment by andrewthetechie** [comment]
https://github.com/andrewthetechie/geekbot-api-py/releases/tag/v0.2.1

Thanks for the fix!
